# Imports

In [1]:
import pandas as pd
import os
import glob
import pandas as pd
from sklearn.model_selection import train_test_split
pd.options.display.max_columns = 10000
import numpy as np

# Read Data

In [2]:
df = pd.read_csv('/home/meghanmergui/Synth20/Create_Synthetic_Games/synth_all.csv')

In [3]:
df.shape

(108000000, 22)

In [4]:
print(df.sigma.unique())
print(df.beta.unique())
print(df.kapa.unique())
print(df.gama.unique())

[1.17 3.5  5.83]
[0.43 1.3  2.17]
[1 2 3]
[1.5  0.33]


In [ ]:
pd.DataFrame(df.loc[(df.sigma == 3.5) & (df.beta == 1.3s) & (df.gama == )])['GameId'].unique()
indiv_games = group_indiv.to_dict()

In [ ]:
indiv_games['GameId'].keys()

# Group by individual type 

In [16]:
group_indiv = pd.DataFrame(df.groupby(['sigma', 'beta', 'kapa', 'gama'])['GameId'].unique())
indiv_games = group_indiv.to_dict()

In [17]:
del group_indiv

In [ ]:
in

In [18]:
indiv_games['GameId'].keys()

dict_keys([(1.17, 0.43, 1, 0.33), (1.17, 0.43, 1, 1.5), (1.17, 0.43, 2, 0.33), (1.17, 0.43, 2, 1.5), (1.17, 0.43, 3, 0.33), (1.17, 0.43, 3, 1.5), (1.17, 1.3, 1, 0.33), (1.17, 1.3, 1, 1.5), (1.17, 1.3, 2, 0.33), (1.17, 1.3, 2, 1.5), (1.17, 1.3, 3, 0.33), (1.17, 1.3, 3, 1.5), (1.17, 2.17, 1, 0.33), (1.17, 2.17, 1, 1.5), (1.17, 2.17, 2, 0.33), (1.17, 2.17, 2, 1.5), (1.17, 2.17, 3, 0.33), (1.17, 2.17, 3, 1.5), (3.5, 0.43, 1, 0.33), (3.5, 0.43, 1, 1.5), (3.5, 0.43, 2, 0.33), (3.5, 0.43, 2, 1.5), (3.5, 0.43, 3, 0.33), (3.5, 0.43, 3, 1.5), (3.5, 1.3, 1, 0.33), (3.5, 1.3, 1, 1.5), (3.5, 1.3, 2, 0.33), (3.5, 1.3, 2, 1.5), (3.5, 1.3, 3, 0.33), (3.5, 1.3, 3, 1.5), (3.5, 2.17, 1, 0.33), (3.5, 2.17, 1, 1.5), (3.5, 2.17, 2, 0.33), (3.5, 2.17, 2, 1.5), (3.5, 2.17, 3, 0.33), (3.5, 2.17, 3, 1.5), (5.83, 0.43, 1, 0.33), (5.83, 0.43, 1, 1.5), (5.83, 0.43, 2, 0.33), (5.83, 0.43, 2, 1.5), (5.83, 0.43, 3, 0.33), (5.83, 0.43, 3, 1.5), (5.83, 1.3, 1, 0.33), (5.83, 1.3, 1, 1.5), (5.83, 1.3, 2, 0.33), (5.83, 1.

In [19]:
len(indiv_games['GameId'][(1.17,0.43, 1,0.33)])

10000

# Create Dataframe

In [20]:
df.columns

Index(['Ha', 'pHa', 'La', 'LotNumA', 'LotShapeA', 'Hb', 'pHb', 'Lb', 'LotNumB',
       'LotShapeB', 'Corr', 'Amb', 'GameId', 'B1', 'sigma', 'kapa', 'beta',
       'gama', 'psi', 'theta', 'wamb', 'Beast1'],
      dtype='object')

## Add PF

In [21]:
PF_games = pd.read_csv('/home/meghanmergui/Synth20/Create_Synthetic_Games/2_Add_PF/Synth10KPF.csv')
print(PF_games.shape)

(10000, 28)


In [22]:
PF_games.head(5)

Ha   pHa  La  LotNumA LotShapeA  Hb   pHb  Lb  LotNumB LotShapeB  Corr  \
0  53  0.25 -20        1         -  86  0.25 -23        1         -     0   
1  42  0.01   9        4    R-skew   9  1.00   9        1         -     0   
2  -4  1.00  -4        1         -   5  0.99 -20        4      Symm     0   
3  13  1.00  13        1         -  54  0.40  -9        1         -     0   
4  -6  1.00  -6        1         -  -6  1.00  -6        8    L-skew     0   

   Amb  diffEV    diffSDs  diffMins  diffMaxs  diffUV  RatioMin  SignMax  \
0    0    6.00  15.588457      -3.0      33.0   15.00  0.869565      1.0   
1    0   -0.33  -3.315283       0.0     -44.0  -28.40  1.000000      1.0   
2    0    8.75   2.632489     -16.0      10.5    4.00  0.200000      1.0   
3    0    3.20  30.863571     -22.0      41.0    9.50  0.000000      1.0   
4    0    0.00  26.172505    -247.0       7.0  -54.75  0.023715      1.0   

   pBbet_Unbiased1  pBbet_UnbiasedFB  pBbet_Uniform  pBbet_Sign1  \
0          -0.4962           -0.5010         0.0014       0.0000   
1          -0.0110           -0.0082        -0.7909       0.0000   
2           0.9804            0.9838         0.5854       0.9910   
3          -0.1992           -0.1986         0.0094      -0.5980   
4           0.7474            0.7520        -0.2656       0.5044   

   pBbet_SignFB  Dom  diffBEV0  diffBEVfb    diffSignEV  
0       -0.0040    0      6.00       6.00  0.000000e+00  
1        0.0000   -1     -0.33      -0.33  7.105427e-15  
2        0.9885    0      8.75       8.75  5.247000e+01  
3       -0.6006    0      3.20       3.20 -7.560000e+01  
4        0.5076    0      0.00       0.00  2.540000e+02

In [23]:
# Merge Dataframe
df = df.merge(PF_games, on=['Ha', 'pHa', 'La', 'LotShapeA', 'LotNumA', 'Hb', 'pHb', 'Lb', 'LotShapeB', 'LotNumB', 
                           'Corr', 'Amb'], how='left')
print(df.shape)

(108000000, 38)


## Encode Lotshape

In [24]:
def lot_shape_convert(lot_shape):
    if lot_shape == '-' : 
        return 1,0,0,0
    elif lot_shape == 'Symm' : 
        return 0,1,0,0
    elif lot_shape == 'L-skew' : 
        return 0,0,1,0
    elif lot_shape == 'R-skew' :
        return 0,0,0,1

In [25]:
df['lot_shape__B'], df['lot_shape_symm_B'], df['lot_shape_L_B'], df['lot_shape_R_B'] = zip(*df['LotShapeB'].map(lot_shape_convert))

In [26]:
df['lot_shape__A'], df['lot_shape_symm_A'], df['lot_shape_L_A'], df['lot_shape_R_A'] = zip(*df['LotShapeA'].map(lot_shape_convert))

In [27]:
df.shape

(108000000, 46)

## x_col, y_col

In [15]:
df.columns

Index(['Ha', 'pHa', 'La', 'LotNumA', 'LotShapeA', 'Hb', 'pHb', 'Lb', 'LotNumB',
       'LotShapeB', 'Corr', 'Amb', 'GameId', 'B1', 'sigma', 'kapa', 'beta',
       'gama', 'psi', 'theta', 'wamb', 'Beast1', 'diffEV', 'diffSDs',
       'diffMins', 'diffMaxs', 'diffUV', 'RatioMin', 'SignMax',
       'pBbet_Unbiased1', 'pBbet_UnbiasedFB', 'pBbet_Uniform', 'pBbet_Sign1',
       'pBbet_SignFB', 'Dom', 'diffBEV0', 'diffBEVfb', 'diffSignEV',
       'lot_shape__B', 'lot_shape_symm_B', 'lot_shape_L_B', 'lot_shape_R_B',
       'lot_shape__A', 'lot_shape_symm_A', 'lot_shape_L_A', 'lot_shape_R_A'],
      dtype='object')

In [13]:
col1 = [ 'Ha', 'pHa', 'La', 'LotNumA', 'lot_shape__A', 'lot_shape_symm_A', 'lot_shape_L_A', 'lot_shape_R_A',
        'Hb', 'pHb', 'Lb', 'LotNumB', 'LotShapeB', 'lot_shape__B', 'lot_shape_symm_B', 'lot_shape_L_B', 'lot_shape_R_B',
        'Corr', 
        'B1', 
        'Beast1',   
        'diffEV', 'diffSDs', 'diffMins', 'diffMaxs', 'diffUV', 'RatioMin', 'SignMax',
        'Dom', 'diffBEV0', 'diffBEVfb', 'diffSignEV']
#         'Amb',
#         'GameId',
#         'psi', 'theta', 'wamb',
#        'pBbet_Unbiased1', 'pBbet_UnbiasedFB', 'pBbet_Uniform', 'pBbet_Sign1', 'pBbet_SignFB',

columns_20= []
for i in range(1,21): 
    columns_20.extend([str(str(co) + '_'+ str(i)) for co in col1])


In [17]:
len(col1)

31

In [14]:
x_col = columns_20
y_col = ['sigma', 'kapa', 'beta', 'gama']

In [20]:
len(x_col)

620

## Create dataframe _ multiprocess

In [26]:
del PF_games

In [15]:
df.shape

(108000000, 22)

In [10]:
def create_MLPdata(df, type_3, i): 
    df_all20 = pd.DataFrame(columns=x_col+y_col)
    for indiv in type_3:
        print(indiv)
        sigma = indiv[0]
        beta = indiv[1]
        kapa =indiv[2]
        gama = indiv[3]

        df_indiv = df.loc[(df.sigma == sigma) & (df.beta == beta) & (df.kapa == kapa) & (df.gama == gama)]
        print(df_indiv.shape[0])
        num_g = 0
        while df_indiv.shape[0] >= 20 : 
            df_20 = df_indiv.sample(20)
            if df_20.GameId.nunique() == 20 : 
                num_g +=1
                df_indiv = df_indiv.drop(df_20.index)
                df_20 = df_20[col1]
                new_row = list(np.reshape(df_20.values, (1,df_20.shape[0]*df_20.shape[1]))[0])
                new_row.extend([sigma, kapa, beta, gama])
                print(len(new_row))
                df_all20.loc[df_all20.shape[0]] = new_row
                print('num_g', num_g)
    print(i)
    print(df_all20.shape)
    print(df_all20.head(5))

    df_all20.to_csv(str('/home/meghanmergui/Synth20/Create_Synthetic_Games/Synth20MLP/synth_20MLP' + str(i) +str('.csv')))


In [11]:
import multiprocessing 
processes = []
all_type = list(indiv_games['GameId'].keys())
for i in range(0,18):
        type_3i = all_type[i*3:(i+1)*3]
        p = multiprocessing.Process(target=create_MLPdata, args=(df, type_3i, i))
        processes.append(p)
        p.start()
        
for process in processes:
    process.join()    


Process Process-1:
Traceback (most recent call last):
  File "/home/meghanmergui@st.technion.ac.il/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/meghanmergui@st.technion.ac.il/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Process Process-2:
Traceback (most recent call last):
  File "<ipython-input-10-f378273d3e64>", line 2, in create_MLPdata
    df_all20 = pd.DataFrame(columns=x_col+y_col)
  File "/home/meghanmergui@st.technion.ac.il/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
NameError: name 'x_col' is not defined
  File "/home/meghanmergui@st.technion.ac.il/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Process Process-3:
  File "<ipython-input-10-f378273d3e64>", line 2, in create_MLPdata
    df_all20 = pd.DataFrame(columns=x_col+y_col)
NameEr

  File "/home/meghanmergui@st.technion.ac.il/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-10-f378273d3e64>", line 2, in create_MLPdata
    df_all20 = pd.DataFrame(columns=x_col+y_col)
Process Process-18:
NameError: name 'x_col' is not defined
Traceback (most recent call last):
  File "/home/meghanmergui@st.technion.ac.il/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/meghanmergui@st.technion.ac.il/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-10-f378273d3e64>", line 2, in create_MLPdata
    df_all20 = pd.DataFrame(columns=x_col+y_col)
NameError: name 'x_col' is not defined


# Save Dataframe 

In [ ]:
df_all.head()

In [ ]:
df_all20.shape

In [ ]:
df_all20.to_csv('/home/meghanmergui/Synth20/Create_Synthetic_Games/synth_20MLP.csv', index = False)

# Create Train and Test

In [ ]:
# Split train and test set 
df_train, df_test = train_test_split(df_all20, test_size=0.01)

In [ ]:
df_train.to_csv('/home/meghanmergui/Synth20/Create_Synthetic_Games/synth_train_20MLP.csv', index = False)

In [ ]:
df_test.to_csv('/home/meghanmergui/Synth20/Create_Synthetic_Games/synth_test_20MLP.csv', index = False)

In [2]:
df_all20.shape

NameError: name 'df_all20' is not defined